name: Publish

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
      contents: write
    defaults:
      run:
        working-directory: ./
      
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    - name: Install Flutter
      uses: subosito/flutter-action@v2     
      
    - name: Publish to pub.dev
      run: flutter pub publish --force
